package jbs.ledger.events.transfers;

public enum AssetTransferCause {
    ORDER_FULFILLED,
    OPTION_EXERCISED,
    BANK_INTEREST,
    BANK_DEPOSIT,
    BANK_WITHDRAWAL,
    CASH_DIVIDEND,
    STOCK_DIVIDEND,
    NOTE_EXPIRED,
    PAY_COMMAND,
    CORPORATION_CREATED,
    FOUNDATION_CREATED,
    NATION_CREATED,
    FEDERATION_CREATED,
    TRUST_CREATED,
    CREDIT_CARD_EXPIRED,
    CREDIT_CARD_SETTLEMENT;

}
