name: Ledger
version: '${project.version}'
main: jbs.ledger.Ledger
api-version: '1.20'
commands:
  create:
    description: 무언가를 생성합니다.
    usage: /create
    aliases: [new, 신규, 추가, 생성]
  gps:
    description: GPS 시스템을 이용합니다. 프리미엄 유저만 이용 가능합니다.
    usage: /gps
    aliases: [g, nav, navi, navigation, 네비, 네비게이션]
  invite:
    description: 조직으로 초대를 보냅니다.
    usage: /invite
    aliases: [invite, h, hire, 초대, 고용]
  kick:
    description: 구성원을 조직에서 추방합니다.
    usage: /kick
    aliases: [k, f, fire, 해고, 해임, 추방]
  message:
    description: 메시지를 발송합니다.
    usage: /message 수신인 내용
    aliases: [m, w, t, msg, dm, 메시지, 디엠]
  deny:
    description: 제안 또는 거래를 거절합니다.
    usage: /deny
    aliases: [n, d, non, nay, decline, 거부, 거절, 아니오]
  punish:
    description: 대상에게 재제를 가합니다.
    usage: /punish
    aliases: [제재, 형벌, 선고]
  reply:
    description: 수신한 메시지에 답장합니다.
    usage: /reply 내용
    aliases: [r, re, 답변 답장]
  teleporthererequest:
    description: 상대방에게 역텔레포트 요청을 보냅니다.
    usage: /teleporthererequest 상대
    aliases: [tpahere, tpaskhere, teleportaskhere, tpaskhere, 역텔포, 역텔레포트]
  teleportrequest:
    description: 상대방에게 텔레포트 요청을 보냅니다. 상대가 법인인 경우 즉시 텔레포트됩니다.
    usage: /teleportrequest 상대
    aliases: [tpr, tpa, tpask, tprequest, teleportask, 텔포, 텔레포트]
  vote:
    description: 주주통회 또는 선거에 참여하거나 안건을 상정합니다.
    usage: /vote
    aliases: [v, votes, voting, elect, election, elections, meeting, 투표, 선거, 의결, 주총, 주주총회, 총회]
  accept:
    description: 제안 또는 거래를 수락합니다.
    usage: /accept
    aliases: [y, a, yay, agree, 동의, 수락, 예]
  directors:
    description: 이사회에 참여하거나 이사회를 관리합니다.
    usage: /directors
    aliases: [d, director, board, 이사, 이사회]
  manage:
    description: 조직이나 기관을 관리합니다.
    usage: /manage
    aliases: [mg, mgm, manage, modity, setting, settings, 설정, 관리]
  members:
    description: 조직이나 기관의 회원(직원)을 관리합니다.
    usage: /members
    aliases: [e, em, employ, employment, m, member, membership, citizen, citizenship, 고용, 직원, 멤버, 시민, 시민권]
  sudo:
    description: 조직이나 기관의 명의로 명령어를 실행합니다.
    usage: /sudo 법인코드 명령어
    aliases: [d, deputy, su, sud, as, ex, exe, execute, 대변, 대신]
  assets:
    description: 자산을 조회합니다.
    usage: /assets
    aliases: [ast, asset, assets, 자산]
  liabilities:
    description: 부채를 조회합니다.
    usage: /liabilities
    aliases: [debt, liability, 부채, 빚]
  cards:
    description: 신용카드/체크카드를 조회 및 관리합니다.
    usage: /cards
    aliases: [card, ccard, dcard, ccards, dcards, creditcard, debitcard, creditcards, debitcards, 카드, 신용카드, 체크카드]
  forwards:
    description: 선도계약을 체결 및 관리합니다.
    usage: /forwards
    aliases: [contract, contracts, forward, 선도, 계약]
  futures:
    description: 선물계약을 관리 및 매매합니다.
    usage: /futures
    aliases: [future, 선물]
  options:
    description: 옵션을 행사, 관리 및 매매합니다.
    usage: /options
    aliases: [o, option, 옵션]
  networth:
    description: 순자산을 조회합니다.
    usage: /networth
    aliases: [nw, worth, 순자산, equity, 자본, capital, 자기자본]
  pay:
    description: 현금을 송금합니다.
    usage: /pay 수신인 금액 [통화코드]
    aliases: [송금, 이체]
  stocks:
    description: 주식을 관리 및 매매합니다.
    usage: /stocks
    aliases: [s, stock, stocks, share, shares, 주식]
  information:
    description: 대상에 관한 정보를 조회합니다.
    usage: /information 대상
    aliases: [i, inf, info, 정보, 조회]
  list:
    description: 특정 유형에 해당하는 검색결과를 전부 조회합니다.
    usage: /list
    aliases: [l, li, ls, list, search, 목록, 검색]
  networthleaderboard:
    description: 순자산 상위 목록을 조회합니다.
    usage: /networthleaderboard
    aliases: [nwl, baltop, bt, balancetop, btop, networthleaderboards, rank, ranking, 순자산상위, 순자산상위목록, 순자산순위]
  premium:
    description: 프리미엄 상태를 확인합니다.
    usage: /premium
    aliases: [프리미엄]
  back:
    description: 이전 위치로 이동합니다.
    usage: /back
    aliases: [b, bk, bck, back, 백, 뒤로]
  balance:
    description: 현금 잔고를 조회합니다.
    usage: /balance
    aliases: [bal, cash, money, m, balance, 잔고, 현금]
  spawn:
    description: 스폰으로 이동합니다.
    usage: /spawn
    aliases: [lobby, 스폰]
  setspawn:
    description: 스폰 지점을 설정합니다.
    usage: /setspawn
    aliases: ss
  pardon:
    description: 유저에 대한 모드 재제를 취소합니다.
    usage: /pardon 유저
    aliases: [pr, prd, pardon]
  cancel:
    description: 취소 가능한 행동을 취소합니다.
    usage: /cancel
    aliases: [c, cn, can, 취소]
  buy:
    description: 자산을 시장가로 매수합니다. 매도호가가 가장 낮은 거래소에 주문이 접수됩니다. 수량 미입력시 전액매수로 간주합니다.
    usage: /buy 종목코드 [수량]
    aliases: [purchase, 구매, 매수]
  sell:
    description: 자산을 시장가로 매도합니다. 매수호가가 가장 높은 거래소에 주문이 접수됩니다. 수량 미입력시 전량매도로 간주합니다.
    usage: /sell 종목코드 [수량]
    aliases: [dump, 판매, 매도]
  creditrating:
    description: 대상의 신용등급을 확인합니다.
    usage: /creditscore [대상]
    aliases: [cs, cscore, cr, crating, crank, creditscore, 신용점수, 신용등급]
  sethome:
    description: 주소지를 등록합니다.
    usage: /sethome
    aliases: [sh, newhome, setaddress, changeaddress, newaddress, changehome, 집설정, 집변경, 주소지설정, 주소지변경]
  deletehome:
    description: 주소지를 삭제합니다.
    usage: /deletehome
    aliases: [dh, delhome, deladdress, deleteaddress, 집삭제, 주소지삭제]
  home:
    description: 주소지로 이동합니다.
    usage: /home
    aliases: [office, hq, address, house, 집, 홈, 사무실]
  price:
    description: 자산의 공정가격을 조회합니다.
    usage: /price
    aliases: [p, pr, price, 가격, 가치, 공정가치, 시장가치, 시장가격, 시장가]




